### PR TITLE
Update version to 0.6.3

### PR DESCRIPTION
**Pull request by jni**
bug fix release

### CODE REVIEW

**Comment by jni** [comment]
@jakirkham sorry to bug you, but any idea what's going wrong [here](https://travis-ci.org/conda-forge/skan-feedstock/jobs/264665408)? All the CI passed without problems on this PR, and release 0.6.3 is [available](https://pypi.python.org/pypi/skan) on PyPI.

(Also, what is the procedure for getting help without naming a specific admin?)

**Comment by jakirkham** [comment]
The token here is expired. Please see the ["Near term" plan]( https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876 ) on how to fix this.

**Comment by jni** [comment]
@jakirkham ouch, thanks!

Just to clarify, if I do nothing, your scripts will fix this for me at some unspecified "mid-term" time? I'm ok with that, as I have a strong suspicion that I am the only user of this package =P, it's pure Python (so PyPI works well), and the paper isn't even submitted yet. Once the paper is submitted, I might be in more of a hurry.

Good luck with it!!!

**Comment by jakirkham** [comment]
Yeah, it's not a great situation.

Some script that is not quite written yet should fix this in the future. One of the core members has written up the initial script, but it still needs some work. Then there is the question of running it without taxing conda-forge and everything connected to it.

Sure if it is not critical to get this out, waiting is a good option. If that changes and this has not been fixed, please let us know.

**Pull request merged**
